# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPiw92KSdHq-U82tcko-NgFcpI6AdVn0
"""

#Prompt the user to enter a positive integer
num_str = input("Enter a positive integer")
#Validate that the input is all digits
if not num_str.isdigit():
  print("Invalid input. Please input  a positive ppositive integer containing only digits ")
else:
  #Initialise a dictionary counts = {}
  counts = {}

  #Iterate over each character in the string (for ch in num_str:):
for ch in num_str:
  counts[ch] = counts.get(ch,0)+1.
  #After iterating through all the digits, printy each digit and its frequency in ascending order:
for ch in sorted(counts.keys()):
  print(f"Digit{ch}: {counts[ch]} times(s)")